[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
des = "0.8.1"

[dependencies]
cipher = "0.4.3"
typenum = "1.15.0"

